### ISSUE TITLE
nicehash support for eth

### ISSUE THREAD

**Issue by mo35** [damominer/damominer#1]
as subj. says , tried on nicehash for eth and f2pool for nhs , no nicehash support , back to nbminer for now , cant compare unfortunately

**Comment by damominer** [comment]
can you provide the nicehash protocal for me ,i will fix it .
damominer888@gmail.com

**Comment by mo35** [comment]
probably can be found here 
https://github.com/nicehash/Specifications

**Comment by damominer** [comment]
you can try the new bin . we have release  ver2.5.8
